apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc-2
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 10Gi # ignored, required
  volumeName: s3-pv-2 # Name of your PV
